name: Node.js Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Run basic test
      run: |
        echo "No test cases yet. Running dummy command."
        node --version

    - name: Build Docker image
      run: |
        docker build -t dev-environment-backend ./backend

# Optional Step to Push to Docker Hub (advanced, if you want)
#    - name: Log in to DockerHub
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}
#    - name: Push image
#      run: |
#        docker push yourdockerhubusername/dev-environment-backend
